// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGAFeP0H6xCqytC5t77L0IBnoiwOvZ_Ng',
    appId: '1:731606760200:web:af9d3caefe0aa9645ecabd',
    messagingSenderId: '731606760200',
    projectId: 'moodify-39d9e',
    authDomain: 'moodify-39d9e.firebaseapp.com',
    storageBucket: 'moodify-39d9e.firebasestorage.app',
    measurementId: 'G-3TN3DVEMGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxgNYNZrrU0iDmaBtF0TZN1nIIWVN8Rz4',
    appId: '1:731606760200:android:c6721bc6f36aea215ecabd',
    messagingSenderId: '731606760200',
    projectId: 'moodify-39d9e',
    storageBucket: 'moodify-39d9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4K2QDD9cOI-NuEPCfCnI_nkpUEDIoxvg',
    appId: '1:731606760200:ios:0777c209518e2d015ecabd',
    messagingSenderId: '731606760200',
    projectId: 'moodify-39d9e',
    storageBucket: 'moodify-39d9e.firebasestorage.app',
    iosBundleId: 'com.example.moodify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4K2QDD9cOI-NuEPCfCnI_nkpUEDIoxvg',
    appId: '1:731606760200:ios:0777c209518e2d015ecabd',
    messagingSenderId: '731606760200',
    projectId: 'moodify-39d9e',
    storageBucket: 'moodify-39d9e.firebasestorage.app',
    iosBundleId: 'com.example.moodify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGAFeP0H6xCqytC5t77L0IBnoiwOvZ_Ng',
    appId: '1:731606760200:web:7e0f48cd9e9f2cfb5ecabd',
    messagingSenderId: '731606760200',
    projectId: 'moodify-39d9e',
    authDomain: 'moodify-39d9e.firebaseapp.com',
    storageBucket: 'moodify-39d9e.firebasestorage.app',
    measurementId: 'G-2PZ3829TDR',
  );
}
